### ISSUE TITLE
Client UI not working

### ISSUE THREAD

**Issue by likku3** [pritunl/pritunl-client#19]
Today i have installed the pritunl-cient on my cent OS 7.Able to use the client in command line but unable to open the UI app.

[root@XYZ ~]# pritunl-client
Usage: pritunl-client [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  daemon   Start client service daemon
  disable  Disable a profile to stop autostart by...
  enable   Enable a profile to autostart by profile ID...
  import   Import new profile archive, conf or uri.
  list     List imported profiles and status
  remove   Remove a profile by profile ID or space...
  start    Start a profile by profile ID or space...
  stop     Stop a profile by profile ID or space...
 
When i click on the Pritunl client icon nothing is getting displayed and can't see any exceptions in logs.

![pritunl](https://cloud.githubusercontent.com/assets/16572724/13601570/0efeb398-e557-11e5-8e8f-843acd22868c.jpg)

**Comment by mostafahussein** [comment]
@likku3 , how did you install pritunl-client ? using `yum`/`apt-get` or by cloning the repository ?

In my case i have installed it through `yum` and i don't have a way to start the GUI unless i have cloned this repository and executed `client_gtk.py`. but i will try to help you in order to identify the problem then  solve it

**Comment by likku3** [comment]
I have cloned the repository and installed the py scripts.After that i am able to see the icon in my pc.

**Comment by zachhuff386** [comment]
The official packages must be used for installing the client.
